# Generated by Django 6.0.3 on 2026-03-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda (R$)')),
                ('imagem_url', models.URLField(verbose_name='Link da Imagem (do fornecedor)')),
                ('link_pagamento', models.URLField(verbose_name='Link do Stripe (Checkout)')),
                ('estoque', models.IntegerField(default=10)),
            ],
        ),
    ]
